### ISSUE TITLE
No background location update

### ISSUE THREAD

**Issue by niteshtak** [intuit/LocationManager#31] opened 2015-03-26 02:50 UTC
can you please add code for background location update also. that would be more helpful

**Comment by smileyborg** [comment] 2015-03-26 15:41
Hi @niteshtak,

Can you please elaborate on what you mean by "background location update"?

The CLLocationManager delegate methods continue to be called while your app is in the background, as long as you have requested the `Always` authorization (which means adding a string for `NSLocationAlwaysUsageDescription`).

**Comment by smileyborg** [comment] 2015-04-03 16:18
Closing this issue until further information is provided.

**Closed by smileyborg** 2015-04-03 16:18 UTC

**Comment by alaaghribi** [comment] 2015-07-13 14:41
Hi @smileyborg , I've added the `NSLocationAlwaysUsageDescription`, entered the sample app in background, and I no longer receive location updates. My question is, perhaps that you're decreasing the accuracy when entering in background ? Or do you `startMonitoringSignificantChanges` ?
(I'm building a navigation app that it continues running in background).

Thank you for your answer/explanation .

**Comment by smileyborg** [comment] 2015-07-13 16:55
Hi @alaaghribi, the one other thing you need to do is add the [location updates background mode](https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/BackgroundExecution/BackgroundExecution.html#//apple_ref/doc/uid/TP40007072-CH4-SW25) to your app. You can find this in Xcode --> your Project --> your app Target --> Capabilities --> Background Modes. This will allow your app to continue running and receiving location updates in the background.

INTULocationManager does not decrease accuracy or act any differently when in the background. Feel free to take a look at the implementation yourself as it's all open source.

**Comment by alaaghribi** [comment] 2015-07-14 01:45
Yes you have reason I forgot this step. I kept testing the Framework, it's simply awesome, however, it's using a lot of battery when in background.. The problem is that there is no way to change accuracy when in background.

**Comment by smileyborg** [comment] 2015-07-14 16:55
@alaaghribi INTULocationManager does not let you control the accuracy requested from location services. If you need access to this, you're best off using Core Location directly.

**Comment by alaaghribi** [comment] 2015-07-14 20:31
@smileyborg Thank you very much for your response.

**Comment by alaaghribi** [comment] 2015-11-13 15:38
Now I can re-use INTULocationManager since we can now change the accuracy ;). Thank you :) !
